Build_Test_Scan

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -135,262 +135,249 @@ jobs:
             npm install
             npm audit fix --audit-level=critical --force
   
-#   deploy-infrastructure:
-#     docker: 
-#       - image: amazon/aws-cli
-#     steps:
-#       - checkout
-#       - run: yum install -y tar gzip
-#       - run:
-#           name: Ensure back-end infrastructure exists
-#           command: |
-#             aws cloudformation deploy \
-#               --template-file .circleci/files/backend.yml \
-#               --tags project=udapeople \
-#               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-#       - run:
-#           name: Ensure front-end infrastructure exist
-#           command: |
-#             aws cloudformation deploy \
-#               --template-file .circleci/files/frontend.yml \
-#               --tags project=udapeople \
-#               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-#               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
-#       - run:
-#           name: Add back-end ip to ansible inventory
-#           command: |
-#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#               --filters "Name=tag:project,Values=udapeople" \
-#               --output text)
-#             echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
-#             cat .circleci/ansible/inventory.txt 
-#       - persist_to_workspace:
-#           root: ~/
-#           paths:
-#             - project/.circleci/ansible/inventory.txt
-#       - destroy-environment
+  deploy-infrastructure:
+    docker: 
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run: yum install -y tar gzip
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople" \
+              --output text)
+            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt 
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      - destroy-environment
   
-#   configure-infrastructure:
-#     docker:
-#       - image: python:3.9.16-alpine3.17
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             apk add --update tar gzip
-#       - attach_workspace:
-#           at: ~/
-#       - add_ssh_keys:
-#           fingerprints: ["52:62:de:8b:52:b2:e4:e9:29:ea:a8:90:2a:99:10:39"] 
-#       - run:
-#           name: Install ansible
-#           command: |
-#             apk add --update ansible
-#       - run:
-#           name: Configure server
-#           command: |
-#             cd backend
-#             echo TYPEORM_CONNECTION=postgres >> ".env"
-#             echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ".env"
-#             echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
-#             echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
-#             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
-#             echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ".env"
-#             echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ".env"
-#             echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
-#             echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
-#             cd ..
-#             cd .circleci/ansible
-#             ansible-playbook -i inventory.txt configure-server.yml
+  configure-infrastructure:
+    docker:
+      - image: python:3.9.16-alpine3.17
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["52:62:de:8b:52:b2:e4:e9:29:ea:a8:90:2a:99:10:39"] 
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update tar gzip --no-cache ansible aws-cli openssh
+      - run:
+          name: Configure server
+          command: |
+            pwd
+            cd .circleci/ansible
+            ls-al
+            ansible-playbook -i inventory.txt configure-server.yml
 
-#   run-migrations:
-#     docker:
-#       - image: circleci/node:14.18.2
-#     steps:
-#       - checkout
-#       - restore_cache:
-#           keys: [backend-build]
-#       - run:
-#           name: Run migrations
-#           command: |
-#             cd backend
-#             npm install
-#             npm run migrations > migrations_dump.txt
-#             cat migrations_dump.txt
+  run-migrations:
+    docker:
+      - image: circleci/node:14.18.2
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            sudo npm install -g npm
+            npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
 
-#       - run:
-#           name: Send migration results to kvdb.io
-#           command: |
-#             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-#             then
-#               curl --insecure https://kvdb.io/ErYb6h5okVatyxDYycE5QA/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-#             else
-#               echo "Migration Failed"
-#             fi
+      - run:
+          name: Send migration results to kvdb.io
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              curl --insecure https://kvdb.io/ErYb6h5okVatyxDYycE5QA/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            else
+              echo "Migration Failed"
+            fi
       
       
-#   deploy-frontend:
-#     docker:
-#       - image: circleci/node:14.18.2
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             sudo apt install -y tar gzip unzip
-#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-#             sudo apt-get install unzip
-#             unzip awscliv2.zip
-#             sudo ./aws/install
-#       - restore_cache:
-#           keys: [frontend-build]
-#       - run:
-#           name: Get backend url
-#           command: |
-#             export BACKEND_IP=$(aws ec2 describe-instances \
-#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#               --filters "Name=tag:project,Values=udapeople" \
-#               --output text)
-#             export API_URL="http://${BACKEND_IP}:3030"
-#             echo $API_URL > url.txt
-#             echo "API_URL = ${API_URL}"
-#             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-#             cat frontend/.env
-#       - persist_to_workspace:
-#           root: ./
-#           paths:
-#             - url.txt
-#       - run:
-#           name: Deploy frontend objects
-#           command: |
-#             cd frontend
-#             npm run build
-#             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-#             aws s3 cp dist s3://udapeople333-533226558473 --recursive
-#       - destroy-environment
-#       - revert-migrations
+  deploy-frontend:
+    docker:
+      - image: circleci/node:14.18.2
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt install -y tar gzip unzip
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            sudo apt-get install unzip
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople" \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $API_URL > url.txt
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - persist_to_workspace:
+          root: ./
+          paths:
+            - url.txt
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople333-533226558473 --recursive
+      - destroy-environment
+      - revert-migrations
 
-#   deploy-backend:
-#     docker:
-#       - image: circleci/node:13.8.0
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             sudo apt install -y tar gzip python3 ansible   
-#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-#             sudo apt-get install unzip
-#             unzip awscliv2.zip
-#             sudo ./aws/install
-#       - add_ssh_keys:
-#           fingerprints: ["52:62:de:8b:52:b2:e4:e9:29:ea:a8:90:2a:99:10:39"] 
-#       - attach_workspace:
-#           at: ~/
-#       - run:
-#           name: Deploy backend
-#           command: |
-#             cd backend
-#             npm install
-#             npm run build
-#             echo build successful      
-#       - run:
-#           name: Configure server
-#           command: |    
-#             pwd
-#             tar -C backend -czvf artifact.tar.gz .
-#       - run:
-#           name: Run Ansible
-#           command: |
-#             cd .circleci/ansible
-#             echo "Contents  of the inventory.txt file is _____________________________________>>"
-#             cat inventory.txt
-#             ansible-playbook deploy-backend.yml -i inventory.txt
-#       - destroy-environment
-#       - revert-migrations
+  deploy-backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt install -y tar gzip python3 ansible   
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            sudo apt-get install unzip
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - add_ssh_keys:
+          fingerprints: ["52:62:de:8b:52:b2:e4:e9:29:ea:a8:90:2a:99:10:39"] 
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Deploy backend
+          command: |
+            cd backend
+            npm install
+            npm run build
+            echo build successful      
+      - run:
+          name: Configure server
+          command: |    
+            pwd
+            tar -C backend -czvf artifact.tar.gz .
+      - run:
+          name: Run Ansible
+          command: |
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is _____________________________________>>"
+            cat inventory.txt
+            ansible-playbook deploy-backend.yml -i inventory.txt
+      - destroy-environment
+      - revert-migrations
 
-#   smoke-test:
-#     docker:
-#       - image: circleci/node:13.8.0
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             sudo apt install -y tar gzip unzip
-#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-#             sudo apt-get install unzip
-#             unzip awscliv2.zip
-#             sudo ./aws/install        
-#       - run:
-#           name: Smoke test backend
-#           command: |
-#             export BACKEND_IP=$(aws ec2 describe-instances \
-#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#               --filters "Name=tag:project,Values=udapeople" \
-#               --output text)
-#             export API_URL="http://${BACKEND_IP}:3030"
-#             echo "${API_URL}"
-#             if curl ${API_URL}/api/status | grep "ok"
-#             then
-#                 echo "Backend smoke test succeeded"
-#                 exit 0
-#             else
-#                 echo "Failed Backend smoke test"
-#                 exit 1
-#             fi
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-#             echo ${URL} 
-#             if curl -s ${URL} | grep "Welcome"
-#             then
-#                 # Change this to 0 after the job fails
-#               exit 1
-#             else
-#               return 1
-#             fi
+  smoke-test:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt install -y tar gzip unzip
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            sudo apt-get install unzip
+            unzip awscliv2.zip
+            sudo ./aws/install        
+      - run:
+          name: Smoke test backend
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople" \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl ${API_URL}/api/status | grep "ok"
+            then
+                echo "Backend smoke test succeeded"
+                exit 0
+            else
+                echo "Failed Backend smoke test"
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 1
+            else
+              return 1
+            fi
       
-#       - revert-migrations 
+      - revert-migrations 
 
-#   cloudfront-update:
-#     docker:
-#       - image: amazon/aws-cli
-#     steps:
-#       - checkout
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       - destroy-environment
-#       - revert-migrations 
+  cloudfront-update:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            # your code here
+      - destroy-environment
+      - revert-migrations 
   
-#   cleanup:
-#     docker:
-#       - image: a
-#     steps:
-#       - checkout
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
+  cleanup:
+    docker:
+      - image: a
+    steps:
+      - checkout
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
      
     
       
@@ -411,19 +398,19 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-#       - deploy-infrastructure:
-#           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-#           filters:
-#             branches:
-#               only: [master]
-#       - configure-infrastructure:
-#           requires: [deploy-infrastructure]
-#       - run-migrations:
-#           requires: [configure-infrastructure]
-#       - deploy-frontend:
-#           requires: [run-migrations]
-#       - deploy-backend:
-#           requires: [run-migrations]
-#       - smoke-test:
-#           requires: [deploy-backend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
+      - smoke-test:
+          requires: [deploy-backend]
       
